### PR TITLE
fix Bean node unnamed (#298)

### PR DESCRIPTION
**Pull request by FrogDevelopper**
Avoid adding `null` in the path of Constraint Validation error

### CODE REVIEW

**Comment by FrogDevelopper** [comment]
to be linked with #298

**Comment by dstepanov** [comment]
Can you please add a test?

**Comment by FrogDevelopper** [comment]
@dstepanov 
Done

**Review by sdelamo — APPROVED** [review]

**Comment by dstepanov** [comment]
Thanks @FrogDevelopper

**Comment by FrogDevelopper** [comment]
@dstepanov 
maybe we should cherry-pick this fix to 4.4.x, no ?

**Pull request merged**
